Feature/sprite
Olha-Sadova/team-project pull request #3
Opened 2022-07-22 17:21 UTC by MaryDorma

ups sag

2022-07-22 20:06 UTC, Olha-Sadova commented on src/images/image.svg
>  <symbol id="icon-arrow" viewBox="0 0 32 32">
icon-arrow

2022-07-22 20:16 UTC, Olha-Sadova requested changes

2022-07-22 20:16 UTC, Olha-Sadova commented on src/images/image.svg
> +<symbol id="icon-arrow" viewBox="0 0 26 32">
icon-arrow? два одинаковых?)

2022-07-22 22:49 UTC, MaryDorma commented on src/images/image.svg
> +<symbol id="icon-arrow" viewBox="0 0 26 32">
cтранно, я добавляла футер на второй..
перезапушила)

2022-07-23 07:52 UTC, Olha-Sadova requested changes

2022-07-23 07:52 UTC, Olha-Sadova commented on src/partials/contacts.html
> +
что за плюсик? может, его удалить надо?

2022-07-23 18:30 UTC, Olha-Sadova approved these changes

2022-07-23 18:44 UTC, merged