created hero section
Olha-Sadova/team-project pull request #7
Opened 2022-07-23 12:55 UTC by MargoTrigub

2022-07-23 18:43 UTC, Olha-Sadova requested changes

2022-07-23 18:43 UTC, Olha-Sadova commented on src/sass/_hero.scss
> +img {
добавь класс имеджу и прописывай стили через класс. Тег имедж используется и в других секциях

2022-07-23 19:30 UTC, MargoTrigub commented on src/sass/_hero.scss
> +img {
Ок, но обычно это глобальные стили которые вписываются в коммон

2022-07-24 06:37 UTC, Olha-Sadova approved these changes

2022-07-24 06:37 UTC, merged